spring:
  application:
    name: plink
  config:
    import:
      - optional:classpath:/application-core.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(V49bXHmsc1mecbDHysu8BfU4pTMBC6uOpO5Mx0iaNWvk7wyRM8IvBvQPKngJ/QDj)
    username: ENC(+LbUdM972QX9ispmT9le4g==)
    password: ENC(OKJwTXnsJjoHaG+74p+6iIalEz0fiunH)
  jackson:
    property-naming-strategy: SNAKE_CASE

# JWT
jwt:
  issuer: ENC(IMwo1Tw7iNk3A6jXShGRktiAyrr4so02)
  secret: ENC(VZ7OOIVlXTNg24ejE1ccGEnw5QA5HhnBkj7mwBm5pQE=)
  cache-key: ENC(jX48JLxlH3OVrbREicVYd2tk4wf2vX9bnba4bqM9Du8=)

# REDIS
redis:
  config:
    host: localhost
    port: 6379
    password:
